### ISSUE TITLE
Change the project name?

### ISSUE THREAD

**Issue by pemo11** [CosmosOS/XSharp#77]
I know this is not an issue so please excuse the misuse.

I was in search for the "real X#" and found this project.

Can't you change the name to something else like XS# oder XAsm#  or something else?

I am using the language X# which was published in 2017 as an open source successor to some of the xBase languages like VO for many years so its really confusing me and for other probably too if there is another tool called X#.

This is also not in the spirit of an Open Source Community in my opion. But I don't know of course who first came up with this name (I know that Microsoft used the term X# for an experimental XML based language many years ago, around 2008?)

I am in no way affialiated with the X# development team and I am NOT acting on their behalf.

Maybe your project, if it is still active, will benefit from a name change too.

Kind regards,
Peter

**Comment by ADev531** [comment]
Probably you'll need to contact adminstrator for now.
(+ This project was older than 2017, You should check CosmosOS repository for first version of X#)

**Comment by zarlo** [comment]
we predate 2017, and well just look at how many projects use the name cosmos. we will not be changing name

**Comment by mterwoord** [comment]
Hi,

We will not be changing project name.

In 2015, there has been contact with the company behind the other project. They tried to trade mark the X# name. They failed to get it, due to prior usage. 
It's Kind of insane to expect the project that first used the name to rename.

With kind regards,
Matthijs ter Woord.
